language: java
jdk:
- openjdk11

addons:
  sonarcloud:
    organization: "ceciliacal"
    token: "9dec0af2e72859868064557aad6dfe58c169a577" 

    

script:
  - ant build
  - sonar-scanner 
  
 