language: java
jdk:
- openjdk8

addons:
  sonarcloud:
    organization: "ceciliacal"
    token: "9dec0af2e72859868064557aad6dfe58c169a577" 

    

install: mvn clean install -q -DskipTests=true


script:  mvn clean verify sonar:sonar -Dsonar.projectKey=ceciliacal_bookkeeperISW2_D2M1 
  
 